schema_version = "1.0.3"

id = "dumb_tools"
version = "1.0.1"
name = "DumbTools"
tagline = "Executes scripts from a predefined folder"
maintainer = "Chris Williamson"
type = "add-on"

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-2.0-or-later"
]
website = "https://github.com/ChrisWilliamson11/DumbTools"

[permissions]
network = "Download updated scripts from GitHub"
