@echo off
echo Starting Megascans processing...

:loop
echo Running Blender...
"C:\Users\User\Downloads\Blender_Launcher_v2.2.0_Windows_x64\daily\blender-4.4.0-alpha+daily.263212c4fa0b\blender.exe" -b -P "j:/DumbTools/DumbTools/Texturing/CreateMegascansBrushes.py"

echo Blender process ended or crashed
echo Waiting 2 seconds before restart...
timeout /t 2

echo Restarting...
goto loop